### ISSUE TITLE
Exception Handler left over on docs

### ISSUE THREAD

**Issue by GeoSot** [BinarCode/laravel-restify#424]
Commit https://github.com/BinarCode/laravel-restify/commit/a616a501eaf522c491eb124e45a62b7b2b890e33#diff-f55db4bc294bbb90108ccfcbdd11881f4707473ad9384b382e2a6b653e118471   removed `exception_handler` configuration, 
but this docs reference  https://restify.binarcode.com/quickstart#exception-handling is left 

edit: this too https://restify.binarcode.com/api/exception-handler#disable-restify-exception-handler

**Comment by binaryk** [comment]
Good check! Will address that, as the documentation is not very up to date now. Thank you!

**Comment by binaryk** [comment]
Fixed https://github.com/BinarCode/laravel-restify/pull/427. Thank you!
