### ISSUE TITLE
Pagination conventions are not aligned with json:api

### ISSUE THREAD

**Issue by GeoSot** [BinarCode/laravel-restify#425]
In the process, to evaluate the package, in order to use it in my company's project, I fell on another little thing

According to https://jsonapi.org/profiles/ethanresnick/cursor-pagination/#auto-id-pagesize   & https://jsonapi.org/format/1.1/#fetching-pagination
pagination related querystrings is suggested to be under `page` key (ex: /example?page[number]=3&page[size]=2)

**Comment by binaryk** [comment]
Thank you for the feedback! The release with fix here https://github.com/BinarCode/laravel-restify/releases/tag/5.5.8
