### ISSUE TITLE
Store on a repository ignores the $fillable on the Model

### ISSUE THREAD

**Issue by MarcelJuice** [BinarCode/laravel-restify#463]
Laravel version 8.83.14
Restify version 6.11

Currently I have a model called `Folder` which doesn't have $fillable nor $guarded defined.
I created a new RepositoryFolder class and defined some rules. 
Now, I can store a new Model with any attributes defined in rules, which ignores $fillable.

Accordingly to the documentation I was expected a MassAssign Exception.

**Comment by binaryk** [comment]
We might add this to the next 8.x release. Although the feature is simply to add, this will be a very high impact upgrade. If you don't want your fields to be populated simply don't add them to the `fields` list, or mark as `->readable()`. Would be helpful to transform this into a discussion - proposal to get others feedback. 

Thank you!
