### ISSUE TITLE
GET /users is always public - it ignores the auth:sanctum middleware

### ISSUE THREAD

**Issue by Shonetow** [BinarCode/laravel-restify#511]
I've just started using this package two days ago and I was reading docs carefully and all over again to figure it out why the `/users` endpoint can be accessed by an unauthenticated user!?

I've set `auth:sanctum` under the middleware in the `restify.php` config file and I've checked other endpoints and they do returns the "Unauthenticated" sanctum message as I expected.

![image](https://user-images.githubusercontent.com/4283547/189241768-4e49ba50-37e6-4c88-8775-5f1a26d04b5a.png)

**Now, if I change the method to POST - sanctum works!**

![image](https://user-images.githubusercontent.com/4283547/189242479-01ad7397-6851-4e86-bf2e-ddff5feb26c0.png)

So, I've created a new repository `Service` just to discover that the same thing happens. So, each `index` action is publicly accessible and ignores the `auth:sanctum` middleware for some reason.

Bonus: [it should be `--all` instead of `--app`](https://restify.binarcode.com/api/repositories#quick-start), right?
Sub-bonus: `Edit this page on GitHub` returns 404

**Comment by binaryk** [comment]
Thanks for the reported issue @Shonetow, we'll investigate that soon.

**Comment by binaryk** [comment]
Hi @Shonetow, it seems that your policy and RestifyServiceProvider allow the `$user` to be `null`. Check the: 

`App\Providers\RestifyServiceProvider` the `gate` method: 

```
    protected function gate(): void
    {
        Gate::define('viewRestify', function ($user) { // Make sure the user is now $user = null here
           return true;
        });
    }
```

And UserPolicy the `allowRestify` method: 

```
    public function allowRestify(User $user): bool // Make sure you don't have `$user = null` here as well
    {
        return true;
    }
```

**Comment by binaryk** [comment]
Thank you! Fixed.
